### PR TITLE
Include "Listen, Think, and Understand" paper 

### PR DESCRIPTION
**Pull request by YuanGongND**
Dear maintainers,

Thanks so much for collecting the very useful list for MLLM.

[Listen, Think, and Understand](https://arxiv.org/pdf/2305.10790.pdf) is a paper about audio instruction tuning. It is one of the first papers on audio large language models. An interactive demo is available online.

Please consider adding it to the list if appropriate. Thanks!

Best,
Yuan

### CODE REVIEW

**Comment by xjtupanda** [comment]
Thanks for sharing! The paper has been added.

**Comment by YuanGongND** [comment]
Hi @xjtupanda,

Thanks so much for adding it! 

The paper actually has a demo. Though we haven't set a permanent host yet, the link can be found on the GitHub repo at https://github.com/YuanGongND/ltu. Could you also add 'https://github.com/YuanGongND/ltu' as the demo link?

(please do not add the direct demo link as it changes every few days.)

Best,
Yuan

**Comment by xjtupanda** [comment]
> Hi @xjtupanda,
> 
> Thanks so much for adding it!
> 
> The paper actually has a demo. Though we haven't set a permanent host yet, the link can be found on the GitHub repo at https://github.com/YuanGongND/ltu. Could you also add 'https://github.com/YuanGongND/ltu' as the demo link?
> 
> (please do not add the direct demo link as it changes every few days.)
> 
> Best, Yuan

Sure! The corresponding item has been updated.

**Comment by YuanGongND** [comment]
Thanks!

**Pull request closed without merging**
